workflows: 单独给r1pluslts开一个docker编译
周三22点开始，使用新设备树

diff --git a/.github/workflows/build-r1_plus_LTS.yml b/.github/workflows/build-r1_plus_LTS.yml
--- a/.github/workflows/build-r1_plus_LTS.yml
+++ b/.github/workflows/build-r1_plus_LTS.yml
@@ -8,7 +8,7 @@
 # Description: Build OpenWrt using GitHub Actions
 #
 
-name: build-rk3328
+name: build-r1pluslts-docker
 
 permissions: write-all
 #开启写权限，防止无法上传到release
@@ -16,22 +16,22 @@ permissions: write-all
 on:
   repository_dispatch:
   workflow_dispatch:
-  # schedule:
-  # - cron: 0 20 * * 1
-   #   分,时,日,月,星期。每周二 20时执行一次 (UTC时间)
+  schedule:
+   - cron: 0 22 * * 2
+   #     分,时,日,月,周。每周三 20时执行一次 (UTC时间)
   
 env:
-  REPO_URL: https://github.com/coolsnowwolf/lede
-  REPO_BRANCH: master
   FREE_DISK_SH: scripts/free_disk_space.sh
   ENV_SH: scripts/environment.sh
+  REPO_URL: https://github.com/coolsnowwolf/lede
+  REPO_BRANCH: master
+  PLATFORM_FILE: configs/r1pluslts-with-docker.txt
+  CONFIG_FILE: configs/packages.txt
   SETTINGS_SH: scripts/init-settings.sh
   PACKAGES_SH: scripts/packages.sh
-  CLASH_CORE_SH: scripts/preset-clash-core-arm64.sh
-  R8152_PATCH: patchs/rk3328/r8152/100-add-LED-configuration-from-OF.patch
-  UBOOT_PATCH: patchs/rk3328/uboot/9999-add-missing-parameters-for-LTS.patch
-  TARGET_PATCH: patchs/rk3328/target/9991-add-missing-parameters-for-LTS.patch
-  USB3_FILE: patchs/rk3328/target/files/phy-rockchip-inno-usb3.c
+  INSTALL5G_SH: scripts/install-5G.sh
+  CLASH_CORE_SH: scripts/preset-clash-core-arm64-L.sh
+  DTS_SH: scripts/r1pluslts/new-dts.sh
   UPLOAD_BIN_DIR: false
   UPLOAD_FIRMWARE: false
   UPLOAD_RELEASE: true
@@ -39,7 +39,7 @@ env:
 
 jobs:
   build:
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-24.04
 
     steps:
     - name: 检查
@@ -55,10 +55,12 @@ jobs:
         chmod +x $ENV_SH && $ENV_SH
         sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
         sudo timedatectl set-timezone "$TZ"
+        docker image prune -a -f
+        docker container prune -f
         sudo mkdir -p /workdir
         sudo chown $USER:$GROUPS /workdir
 
-    - name: 检查空间使用情况
+    - name: 检查空间使用情况1
       if: (!cancelled())
       run: df -hT
 
@@ -67,31 +69,36 @@ jobs:
       run: |
         git clone $REPO_URL -b $REPO_BRANCH openwrt
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
-        cd openwrt
-        echo "src-git opp https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> ./feeds.conf.default
 
     - name: 开启缓存
       uses: klever1988/cachewrtbuild@main
       with:
         ccache: 'true'
-        mixkey: 'armv8'
+        mixkey: 'r1pluslts'
         prefix: ${{ github.workspace }}/openwrt
 
-    - name: 更新 & 安装 feeds & 执行脚本
+    - name: 安装 feeds
       run: |
         cd openwrt
         ./scripts/feeds update -a
         ./scripts/feeds install -a
+
+    - name: 导入补丁和配置 & 执行脚本
+      run: |
+        [ -d files ] && mv files openwrt/files || echo "files not found"
+        [ -f $PLATFORM_FILE ] && cat $PLATFORM_FILE >> openwrt/.config
+        [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
+        [ -f $CONFIG_5G ] && cat $CONFIG_5G >> openwrt/.config
+        cd openwrt
+        rm target/linux/rockchip/patches-*/991-arm64-dts-rockchip-add-more-cpu-operating-points-for.patch || true
+        chmod +x $GITHUB_WORKSPACE/$INSTALL5G_SH && $GITHUB_WORKSPACE/$INSTALL5G_SH
         chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
         chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
         chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH
+        chmod +x $GITHUB_WORKSPACE/$DTS_SH && $GITHUB_WORKSPACE/$DTS_SH
 
-    - name: 导入补丁和配置 & 下载文件
+    - name:  下载文件
       run: |
-        [ -e files ] && mv files openwrt/files
-        cat configs/rk3328.txt >> openwrt/.config
-        cat configs/packages.txt >> openwrt/.config
-        [ -e $UBOOT_PATCH ] && mv $UBOOT_PATCH openwrt/package/boot/uboot-rockchip/patches
         cd openwrt
         make defconfig
         make download -j8 V=10
@@ -106,7 +113,7 @@ jobs:
         make -j$(($(nproc)+1)) || make -j$(nproc) || make -j1 V=s
         echo "status=success" >> $GITHUB_OUTPUT
 
-    - name: 空间使用情况
+    - name: 空间使用情况2
       if: (!cancelled())
       run: df -hT
 
@@ -141,11 +148,11 @@ jobs:
       id: tag
       if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
       run: |
-        echo -e "✅ lede主线源码rk3328平台\nℹ 长时间无法启动请尝试重启或重刷\n🍃 如出现不稳定可尝试cpu降频" >> release.txt
-        echo "release_tag=$(date +"%Y.%m.%d_rk3328")" >> $GITHUB_OUTPUT
+        echo -e "🎉 香橙派R1 Plus系列带docker版本\n✅ 主线源码\n🍃 如出现不稳定可尝试cpu降频\n❗️ ip地址 : 192.168.8.1" >> release.txt
+        echo "release_tag=$(date +"%Y.%m.%d_r1plus")" >> $GITHUB_OUTPUT
         echo "status=success" >> $GITHUB_OUTPUT
 
-    - name: 上传固件发布
+    - name: 上传固件到发布
       uses: softprops/action-gh-release@v2.0.4
       if: steps.tag.outputs.status == 'success' && !cancelled()
       env:
@@ -155,16 +162,16 @@ jobs:
         body_path: release.txt
         files: ${{ env.FIRMWARE }}/*
 
-    - name: 删除旧发布的固件
+    - name: 删除以前发布的固件
       uses: dev-drprasad/delete-older-releases@v0.3.3
       if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
       with:
-        keep_latest: 10
+        keep_latest: 15
         delete_tags: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: 删除过时工作流程
+    - name: 删除以前的工作流程
       uses: Mattraks/delete-workflow-runs@v2
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
